title: L.Eduardo Cardozo - Blog
author: Luiz Eduardo Cardozo
email: eduard.cardoz@gmail.com
description: > # this means to ignore newlines until "baseurl:" 
  Olá, me chamo Luiz Eduardo Cardozo, e esse é o meu blog!

theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
